# Stage 1: Build
FROM node:lts-bullseye as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Run
FROM ghcr.io/puppeteer/puppeteer:latest
WORKDIR /app

# Copy the built JS files from the build stage
COPY --from=build /app/dist /app
# Copy the node_modules from the build stage
COPY --from=build /app/node_modules /app/node_modules
# Copy all .yml files
COPY --from=build /app/*.yml /app

CMD ["node", "app.js"]
